### ISSUE TITLE
Make the Text/Experiment/Trial Lifecycle More Flexible and Abstract

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/benchflow#332]
Limitations in experiment-manager:
1. fixed number of trials, executed one-by-one (also impacting other part of the code, e.g., https://github.com/benchflow/benchflow/pull/334/files#diff-ff34c5393d21f379f13593e1464fae7eR114 and https://github.com/benchflow/benchflow/pull/334/files#diff-98d4fb8ca0559caf9044c6159af487caR193)
2. no internal control of which experiment is executed (need `TaskScheduler`) (https://github.com/benchflow/benchflow/issues/319)
3. polling of Faban since there is no faban-manager yet
4. converts to previous DSL version for compatibility with driver-maker
5. limited handling of fatal failure (e.g. only trial had failure more than # trial retries)

Moreover we have a strong assumption about the last executed trial etc in the code, that has to be removed, we need to always track the current executing trial / exp / ... and pass the information so that we can avoid the assumption that things happen 1 at a time in a given order (e.g., https://github.com/benchflow/benchflow/pull/291/commits/d661ab1aa5e8a0961006f842e66624adea2e53f9#diff-1964e9152945e64f3ea2b053d4ac9409R45). This is related to: https://github.com/benchflow/benchflow/issues/239.

**Comment by jeppe-style** [comment]
limitations in experiment-manager:
- fixed number of trials, executed one-by-one
- no internal control of which experiment is executed (need `TaskScheduler`) (https://github.com/benchflow/benchflow/issues/319)
- polling of Faban since there is no faban-manager yet
- converts to previous DSL version for compatibility with driver-maker
- limited handling of fatal failure (e.g. only trial had failure more than # trial retries)

**Comment by VincenzoFerme** [comment]
@jeppe-style describe the same assumptions you have in the test manager.

**Comment by VincenzoFerme** [comment]
@jeppe-style could you please comment on this so I know what is actually left, and what we implemented?

**Comment by jeppe-style** [comment]
@VincenzoFerme As I can see most of the items have been implemented.
3. this is now in a separate part in the EM so that it can be easily moved to a separate library/service, although we also need to work on https://github.com/benchflow/benchflow/issues/500
4. this still happens since the DM is not updated yet

**Comment by VincenzoFerme** [comment]
Take also into account to refactor the experiment Manager to better separate states and handling.
